language: node_js
node_js:
  - lts/*

branches:
  only:
    - prod

after_success:
  # Change brnach
  - git checkout origin ${GIT_BRANCH}
  # Run build command
  - yarn build
  # Remove all directories/files not matching 'dist' & '.git'
  - find ./ -maxdepth 1 ! \( -name 'dist' -o -name '.git' \) -exec rm -rf {} \;
  # Move dist dir files outside to current context
  - mv ./dist/* ./ && rmdir dist
  # Change git origin to target repo
  - git remote rm origin && git remote add origin https://username:${GH_TOKEN}@github.com/${GH_TARGET_REPO}
  - git add .
  - git commit -m "Completed Travis-CI automated build"
  - git checko
  - git push -fq origin ${GIT_BRANCH}
