language: node_js
node_js:
  - lts/*

branches:
  only:
    - prod

after_success:
  # Remove all directories/files not matching 'dist' & '.git'
  - find . ! \( -name 'dist' -o -name '.git' \)
  # Move dist dir files outside to current context
  - mv ./dist/* ./ && rmdir dist
  # Change git origin to target repo
  - git remote rm origin && git remote add origin https://username:${GH_TOKEN}@github.com/${GH_TARGET-REPO}
  - git add .
  - git commit -m "Completed Travis-CI automated build"
  - git push -fq origin ${GIT_BRANCH}
